title: Machine Learning Ops
subtitle: Use GitHub to facilitate automation, collaboration and reproducibility in your machine learning workflows.
email: ""
description: A collection of resources on how to facilitate Machine Learning Ops with GitHub.
logo: "/assets/images/Data-driven-recommendations.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mlops-github.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: github
github_username:  github
excerpt_separator: <!--more-->
environment: 'dev'

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  team:
    output: true
  pages:
    output: true
  docs:
    output: true
    sort_by: order_n

defaults:
  - scope:
      path: ""
      type: "team"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "docs"
  - scope:
      path: ""
    values:
      layout: "document"


google_analytics: UA-57531313-6

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - README.md
  - requirements.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
